create table SanPham (
    MaSP NUMBER GENERATED BY DEFAULT AS IDENTITY not null primary key,
    TenSP VARCHAR2(100),
    DvTinh VARCHAR2(20),
    GiaBan FLOAT
)

create table NhaCungCap (
    MaNCC NUMBER GENERATED BY DEFAULT AS IDENTITY not null primary key,
    TenNCC VARCHAR2(200),
    DiaChi VARCHAR2(200),
    DienThoai VARCHAR2(20)
)

create table PhieuNhap (
    MaPN NUMBER GENERATED BY DEFAULT AS IDENTITY not null primary key,
    NgayNhap DATE,
    MaNCC int,
    FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)
)

create table CTPhieuNhap (
    MaPN Number NOT NULL,
    MaSP Number NOT NULL,
    SLNhap int,
    DGNhap float,
    primary key(MaPN, MaSP)
)

create table PhieuXuat (
    MaPX NUMBER GENERATED BY DEFAULT AS IDENTITY not null primary key,
    NgayXuat DATE,
    TenKH VARCHAR2(200)
)

create table CTPhieuXuat (
    MaPX NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SLXuat int,
    DGXuat float,
    primary key(MaPX, MaSP)
)









